languageCode = "en-us"
title = "Matthew Landers - Digital Designer"
theme = "mlanders"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
paginate = 10
copyright = "© 2017 Copyright Text"
canonifyurls = true
baseurl = "https://mtl87.github.io"
googleAnalytics = "UA-88462119-1"

# Nav
[[menu.header]]
  name = "Contact"
  weight = 1
  url = "mailto:mlanders87@gmail.com"
[[menu.header]]
  name = "Resume"
  weight = 2
  url = "img/matthew-landers-resume.pdf"
  identifier = "resume"

# Footer Nav
[[menu.footer]]
  name = "LinkedIn"
  weight = 1
  url = "https://www.linkedin.com/in/mtlanders"
  identifier = "linkedin"
[[menu.footer]]
  name = "Dribbble"
  weight = 2
  url = "https://dribbble.com/landahhs"
  identifier = "dribbble"
[[menu.footer]]
  name = "GitHub"
  weight = 3
  url = "https://github.com/mtl87?tab=overview&from=2016-08-01&to=2016-08-31&utf8=%E2%9C%93"
  identifier = "github"
[[menu.footer]]
  name = "Instagram"
  weight = 4
  url = "https://www.instagram.com/landahhs/"
  identifier = "instagram"
